repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Latest Ruff version as of April 2025
    rev: v0.11.7
    hooks:
      # Run the linter
      - id: ruff
      #   args: [--fix]
      # Run the formatter
      - id: ruff-format
